INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [165945]
INFO:     Stopping reloader process [165917]
2025-06-19 16:42:25.815 | INFO     | __main__:<module>:44 - Uvicorn stopped
2025-06-19 16:42:27.383 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [166013] using StatReload
INFO:     Started server process [166016]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/resources/service.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [166016]
INFO:     Started server process [166147]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/resources/service.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [166147]
INFO:     Started server process [166157]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/resources/service.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [166157]
INFO:     Started server process [166168]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/resources/service.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [166168]
INFO:     Started server process [166186]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [166186]
INFO:     Stopping reloader process [166013]
2025-06-19 16:53:19.576 | INFO     | __main__:<module>:44 - Uvicorn stopped
2025-06-19 16:53:23.139 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [166861] using StatReload
INFO:     Started server process [166921]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/routers/client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [166921]
INFO:     Started server process [168981]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/asgi_correlation_id/middleware.py", line 90, in __call__
    await self.app(scope, receive, handle_outgoing_request)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/api/v2ray/routers/client.py", line 27, in create_v2ray_user
    server_id=data.server_id,
              ^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/pydantic/main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'V2RayUserFromDB' object has no attribute 'server_id'
WARNING:  StatReload detected changes in 'api/v2ray/resources/schemas/v2ray_schemas.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [168981]
INFO:     Started server process [169362]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/resources/schemas/v2ray_schemas.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169362]
INFO:     Started server process [169375]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/resources/schemas/v2ray_schemas.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169375]
INFO:     Started server process [169392]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169392]
INFO:     Stopping reloader process [166861]
2025-06-19 17:19:12.764 | INFO     | __main__:<module>:44 - Uvicorn stopped
2025-06-19 17:19:13.983 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [169530] using StatReload
INFO:     Started server process [169545]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/routers/client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169545]
INFO:     Started server process [169626]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'api/v2ray/routers/client.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169626]
INFO:     Started server process [169662]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169662]
INFO:     Stopping reloader process [169530]
2025-06-19 17:20:11.922 | INFO     | __main__:<module>:44 - Uvicorn stopped
2025-06-19 17:20:13.423 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [169697] using StatReload
INFO:     Started server process [169711]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/asgi_correlation_id/middleware.py", line 90, in __call__
    await self.app(scope, receive, handle_outgoing_request)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/api/v2ray/routers/client.py", line 26, in create_v2ray_user
    status = await service.V2RayProccessor.create_v2ray_user(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: V2RayProccessor.create_v2ray_user() missing 1 required positional argument: 'self'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/asgi_correlation_id/middleware.py", line 90, in __call__
    await self.app(scope, receive, handle_outgoing_request)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/personal/bot_bulder_v1.1/vpn/api/v2ray/routers/client.py", line 26, in create_v2ray_user
    status = await service.V2RayProccessor.create_v2ray_user(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: V2RayProccessor.create_v2ray_user() missing 1 required positional argument: 'self'
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [169711]
INFO:     Stopping reloader process [169697]
2025-06-19 17:25:16.124 | INFO     | __main__:<module>:44 - Uvicorn stopped
2025-06-19 17:58:15.382 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:18.020 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:21.254 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:23.551 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:25.651 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:27.788 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:30.033 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:32.426 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:35.828 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:37.902 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:40.117 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:42.447 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:44.998 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:48.592 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:51.354 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:53.816 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:56.422 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:58:59.402 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:02.332 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:04.694 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:07.119 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:09.420 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:11.764 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:14.192 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:17.436 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:19.761 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:21.835 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:24.136 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:26.233 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:28.561 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:29.836 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:31.906 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:34.175 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:37.545 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:39.620 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:40.922 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:43.117 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:45.654 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:47.900 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:51.080 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:53.405 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:56.961 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 17:59:59.674 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:02.333 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:05.875 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:08.255 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:10.904 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:13.527 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:15.745 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:18.061 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:20.280 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:23.079 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:26.300 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:28.525 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:30.975 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:33.516 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:36.850 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:39.257 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:41.488 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:43.769 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:45.925 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:48.196 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:50.985 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:52.329 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:55.144 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:00:58.358 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:00.713 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:03.927 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:06.131 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:08.614 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:12.215 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:13.771 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:16.214 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:18.532 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:21.089 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:24.271 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:27.684 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:30.097 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:32.365 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:33.865 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:37.270 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:39.625 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:41.828 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:44.251 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:46.591 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:49.198 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:52.562 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:56.100 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:01:59.423 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:01.778 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:04.051 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:06.358 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:09.568 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:11.892 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:15.518 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:18.787 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:21.244 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:23.984 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:26.329 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:29.248 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:31.994 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:35.785 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:39.391 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:43.385 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:45.833 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:47.897 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
ERROR:    [Errno 98] Address already in use
2025-06-19 18:02:51.340 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [175972] using StatReload
INFO:     Started server process [175981]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [175981]
INFO:     Stopping reloader process [175972]
2025-06-19 18:02:58.419 | INFO     | __main__:<module>:44 - Uvicorn stopped
2025-06-19 18:12:43.788 | INFO     | __main__:<module>:35 - Starting debug uvicorn
INFO:     Will watch for changes in these directories: ['/personal/bot_bulder_v1.1/vpn']
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [177996] using StatReload
INFO:     Started server process [178053]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
